name = "CreateTobi"
author = "TobiHDD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3adaf8a848a6f12bed156f511a89051542a67404fdb8ae0671ded9a2121baa94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
