name = "CreateTobi"
author = "TobiHDD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d23473ebc281b1a46712ba885a7ebf1b9fb5001323c03d4ba462d66ddb20db4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
