name = "CreateTobi"
author = "TobiHDD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0feb197d99fd8c94fcf7a87fffb08b5a0284e0f85a43dca8d0daa1afd8b825af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
